[package]
name = "main_project"
version = "0.1.0"
authors = ["m-p-b <m-p-b@hotmail.co.uk>"]
license = "MIT"

[[bin]]
#name = "lesson_0"
#path = "src/TinyRenderer/lesson_0.rs"
name = "SparkEngine"
path = "src/main.rs"

#[dependencies.glfw]
#git = "https://github.com/bjz/glfw-rs.git"

#[dependencies.gl]
#git = "https://github.com/bjz/gl-rs"

# [dependencies.sdl2]
# version = "0.32.2"
# features = ["bundled", "static-link"]

[dependencies]
#internal dependancies
spark_engine = { path = "mylibs/spark_engine" }
#external dependancies
#imgui = "0.2"
#imgui-sys = "*"
# imgui-sdl2 = "0.7.0"
gl = "0.10.0"
#imgui-opengl-renderer = "0.6"
glfw = "*"
# image = "0.22.3"
# tobj = "0.1.11"
#libc = "*"

[build-dependencies]
#gcc = "*"