[package]
name = "main_project"
version = "0.1.0"
authors = ["m-p-b <m-p-b@hotmail.co.uk>"]
license = "MIT"

[[bin]]
name = "SparkEngine"
path = "src/main.rs"

[dependencies.sdl2]
version = "0.34.2"
features = ["bundled", "static-link"]

[dependencies]
gl = "0.10.0"
imgui = "0.4.0"
imgui-sdl2 = "0.11.0"
imgui-opengl-renderer = "0.8"