[package]
name = "sparky_engine"
version = "0.1.0"
authors = ["m-p-b <m-p-b@hotmail.co.uk>"]
build = "build.rs"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
